<?php
/**
 * Implementation of hook_feeds_plugins().
 */
function alingsasintra_jobfeedreader_feeds_plugins() {
  $info = array();
  $info['AditrorecruitFeedFetcher'] = array(
    'name' => 'Aditrorecruit Feed Fetcher',
    'description' => 'Parses Aditrorecruit Feed.',
      'handler' => array(
          'parent' => 'FeedsFetcher', // This is the key name, not the class name.
          'class' => 'AditrorecruitFeedFetcher',
          'file' => 'AditrorecruitFeedFetcher.inc',
          'path' => drupal_get_path('module', 'alingsasintra_jobfeedreader'),
      ),
  );
  return $info;
}

function alingsasintra_jobfeedreader_enable() {
  //clear the cache to display in Feeds as available plugin.
  cache_clear_all('plugins:feeds:plugins', 'cache');
}
?>