#!/usr/bin/env sh

echo "Checking deploy state..."

while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    if [ -d "/usr/local/alingsasroot/wwwtest/git/${branch}"  ]; then
        unset GIT_DIR
        unset GIT_WORK_TREE
        cd "/usr/local/alingsasroot/wwwtest/git/${branch}"
        git pull origin $branch
        echo "${branch} was deployed."
    fi
done

