<?php
/**
 * @file
 * Install, update and uninstall functions
 *
 */


/**
 * Implementation of hook_enable().
 */
function alingsasintra_enable() {
}

/**
 * Implementation of hook_disable().
 */
function alingsasintra_disable() {
}

/**
 * Implementation of hook_uninstall().
 */
function alingsasintra_uninstall() {
  $ret = array();
  return $ret;
}

/**
 * Implementation of hook_install().
 */
function alingsasintra_install() {
  $ret = array();
  return $ret;
}